/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Generations/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of a text-to-speech generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EstimateCostRequest"];
                    "text/json": components["schemas"]["EstimateCostRequest"];
                    "application/*+json": components["schemas"]["EstimateCostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostEstimateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user's generation history */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    status?: components["schemas"]["GenerationStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerationResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Start a new text-to-speech generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateGenerationRequest"];
                    "text/json": components["schemas"]["CreateGenerationRequest"];
                    "application/*+json": components["schemas"]["CreateGenerationRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Generations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status and details of a generation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerationResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Cancel a pending or in-progress generation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Generations/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit feedback for a generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmitFeedbackRequest"];
                    "text/json": components["schemas"]["SubmitFeedbackRequest"];
                    "application/*+json": components["schemas"]["SubmitFeedbackRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all available voices */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    provider?: components["schemas"]["Provider"];
                    language?: string;
                    gender?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoiceResponsePagedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Voices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific voice by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoiceResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Voices/by-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get voices grouped by provider */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ElevenLabs?: components["schemas"]["VoiceResponse"][];
                            OpenAI?: components["schemas"]["VoiceResponse"][];
                            GoogleCloud?: components["schemas"]["VoiceResponse"][];
                            AmazonPolly?: components["schemas"]["VoiceResponse"][];
                            FishAudio?: components["schemas"]["VoiceResponse"][];
                            Cartesia?: components["schemas"]["VoiceResponse"][];
                            Deepgram?: components["schemas"]["VoiceResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Voices/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh voice catalog from all providers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe checkout session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CheckoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutSessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available credit packs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditPacksResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        // TODO: Regenerate from API spec — manual edit for successUrl/cancelUrl
        CheckoutRequest: {
            priceId: string;
            /** @description URL to redirect on successful payment */
            successUrl: string;
            /** @description URL to redirect on cancelled payment */
            cancelUrl: string;
        };
        CheckoutSessionResponse: {
            checkoutUrl: string;
        };
        CreditPacksResponse: {
            packs: components["schemas"]["CreditPack"][];
        };
        CreditPack: {
            id: string;
            name: string;
            credits: number;
            price: number;
            priceId: string;
            description: string;
        };
        Payment: {
            id: string;
            packName: string;
            creditsAdded: number;
            amountPaid: number;
            currency: string;
            status: "completed" | "pending" | "failed" | "refunded";
            createdAt: string;
        };
        PaymentHistoryResponse: {
            payments: components["schemas"]["Payment"][];
        };
        CostEstimateResponse: {
            /** Format: int32 */
            characterCount: number;
            /** Format: int32 */
            estimatedChunks: number;
            /** Format: double */
            estimatedCost: number;
            /** Format: int32 */
            creditsRequired: number;
            currency: string | null;
            recommendedProvider?: components["schemas"]["Provider"];
            providerEstimates?: components["schemas"]["ProviderEstimate"][] | null;
        };
        CreateGenerationRequest: {
            text: string | null;
            /** Format: uuid */
            voiceId: string;
            routingPreference?: components["schemas"]["RoutingPreference"];
            audioFormat?: string | null;
            callbackUrl?: string | null;
        };
        ErrorResponse: {
            code: string | null;
            message: string | null;
            detail?: string | null;
            traceId?: string | null;
            validationErrors?: components["schemas"]["ValidationError"][] | null;
        };
        EstimateCostRequest: {
            text: string | null;
            /** Format: uuid */
            voiceId?: string | null;
            provider?: components["schemas"]["Provider"];
            routingPreference?: components["schemas"]["RoutingPreference"];
        };
        GenerationResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["GenerationStatus"];
            /** Format: int32 */
            characterCount: number;
            /** Format: int32 */
            progress: number;
            /** Format: int32 */
            chunkCount?: number;
            /** Format: int32 */
            chunksCompleted?: number;
            provider?: components["schemas"]["Provider"];
            audioUrl?: string | null;
            audioFormat?: string | null;
            /** Format: int32 */
            audioDurationMs?: number | null;
            /** Format: double */
            estimatedCost?: number | null;
            /** Format: double */
            actualCost?: number | null;
            errorMessage?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
        };
        GenerationResponsePagedResponse: {
            items: components["schemas"]["GenerationResponse"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages?: number;
            readonly hasNextPage?: boolean;
            readonly hasPreviousPage?: boolean;
        };
        /** @enum {string} */
        GenerationStatus: "Pending" | "Analyzing" | "Chunking" | "Processing" | "Merging" | "Completed" | "Failed" | "Cancelled";
        /** @enum {string} */
        Provider: "ElevenLabs" | "OpenAI" | "GoogleCloud" | "AmazonPolly" | "FishAudio" | "Cartesia" | "Deepgram";
        ProviderEstimate: {
            provider: components["schemas"]["Provider"];
            /** Format: double */
            cost: number;
            /** Format: int32 */
            creditsRequired: number;
            /** Format: int32 */
            estimatedDurationMs: number;
            qualityTier: string | null;
            isAvailable?: boolean;
        };
        /** @enum {string} */
        RoutingPreference: "Cost" | "Quality" | "Speed" | "Balanced";
        SubmitFeedbackRequest: {
            /** Format: int32 */
            rating?: number | null;
            comment?: string | null;
        };
        ValidationError: {
            field: string | null;
            message: string | null;
        };
        VoiceResponse: {
            /** Format: uuid */
            id: string;
            name: string | null;
            description?: string | null;
            provider: components["schemas"]["Provider"];
            language?: string | null;
            accent?: string | null;
            gender?: string | null;
            ageGroup?: string | null;
            useCase?: string | null;
            previewUrl?: string | null;
            /** Format: double */
            costPerThousandChars: number;
        };
        VoiceResponsePagedResponse: {
            items: components["schemas"]["VoiceResponse"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages?: number;
            readonly hasNextPage?: boolean;
            readonly hasPreviousPage?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
