// Auto-generated by openapi-typescript
// Run: pnpm generate:api --spec=http://localhost:5000/swagger/v1/swagger.json
//
// This file will be overwritten when regenerating from the backend OpenAPI spec.
// Do not edit manually.

export interface paths {
  // Types will be generated from backend OpenAPI spec
}

export interface components {
  schemas: Record<string, unknown>;
}
